language: objective-c

install:
  - echo noop

script:
  - brew update
  - brew install ghc
  - brew install cabal-install
  - cabal update && cabal install && cabal install --only-dependencies --enable-tests
  - cabal clean && cabal test
  - cabal install
  - (cd hspec-discover/example/ && cabal test)
  - (cd hspec-discover/integration-test/ && cabal test)
  - test/regression/issue-169/run.sh
